import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {

    //Only declare versions here if required for buildscript dependencies
    ext.navigationVersion = '2.8.4'
    ext.hiltVersion = '2.56.2'
    ext.googleServicesVersion = '4.3.12'


    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hiltVersion"
        classpath "com.google.gms:google-services:$googleServicesVersion"
        classpath "com.google.firebase:firebase-crashlytics-gradle:3.0.4"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

